# Generated by Django 4.2.7 on 2026-01-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(default="منصة الاختبارات الذكية", max_length=255),
                ),
                ("two_factor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "system_icon",
                    models.ImageField(blank=True, null=True, upload_to="system_icons/"),
                ),
            ],
        ),
    ]
