# Generated by Django 4.2.7 on 2026-01-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="two_factor_app_password",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
