# Generated by Django 4.2.7 on 2026-01-07 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_systemsettings_two_factor_app_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="auto_fail_on_cheating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="auto_proctoring",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="late_join_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exam",
            name="marking_type",
            field=models.CharField(
                choices=[("equal", "Equal"), ("per_question", "Per question")],
                default="per_question",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="shuffle_questions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="total_mark",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="subject_images/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="core.subject",
            ),
        ),
    ]
