# Generated by Django 4.2.7 on 2026-01-07 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_question_questionchoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="core.subject",
            ),
        ),
    ]
