# Generated by Django 4.2.7 on 2026-01-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="core.message",
            ),
        ),
    ]
