# Generated by Django 4.2.7 on 2026-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_studentjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentjoinrequest",
            name="source",
            field=models.CharField(
                choices=[
                    ("from_student", "From student"),
                    ("from_teacher", "From teacher"),
                ],
                default="from_student",
                max_length=20,
            ),
        ),
    ]
