# Generated by Django 4.2.7 on 2026-01-09 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_examquestion_studentexam_studentanswer_examevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="subject_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
