# Generated by Django 4.2.7 on 2026-01-09 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_alter_exam_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="allowed_students",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_exams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
