# Generated by Django 4.2.7 on 2026-01-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_studentexam_last_activity_at_examnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="model_answer",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="الإجابة النموذجية (للأسئلة المقالية)",
            ),
        ),
    ]
