# Generated by Django 4.2.7 on 2026-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_question_model_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="pass_mark",
            field=models.PositiveIntegerField(
                default=50, help_text="Passing percentage (0-100)"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
