# Generated by Django 4.2.7 on 2026-01-14 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0019_exam_pass_mark_alter_exam_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProctorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("camera_enabled", models.BooleanField(default=False)),
                ("microphone_enabled", models.BooleanField(default=False)),
                (
                    "last_snapshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="proctor_snapshots/%Y/%m/%d/"
                    ),
                ),
                ("last_snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("snapshots_count", models.IntegerField(default=0)),
                ("warnings_count", models.IntegerField(default=0)),
                ("peer_connection_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctor_sessions",
                        to="core.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctor_sessions",
                        to="core.studentexam",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="ProctorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="proctor_snapshots/%Y/%m/%d/")),
                ("faces_detected", models.IntegerField(default=0)),
                ("suspicious", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.proctorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProctorAudioStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("offer_sdp", models.TextField(blank=True)),
                ("answer_sdp", models.TextField(blank=True)),
                ("ice_candidates", models.JSONField(blank=True, default=list)),
                ("bytes_received", models.BigIntegerField(default=0)),
                ("packets_lost", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_stream",
                        to="core.proctorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
