# Generated by Django 4.2.7 on 2026-01-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supervisor_app_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Supervisor app notifications"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="supervisor_email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Supervisor email notifications"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_app_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Teacher app notifications"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Teacher email notifications"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                default="student",
                max_length=10,
                verbose_name="Role",
            ),
        ),
    ]
