# Generated by Django 4.2.7 on 2026-01-08 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_supervisor_app_notifications_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_submissions_email", models.BooleanField(default=True)),
                ("exam_submissions_app", models.BooleanField(default=True)),
                ("student_messages_email", models.BooleanField(default=True)),
                ("student_messages_app", models.BooleanField(default=True)),
                ("cheating_attempts_email", models.BooleanField(default=True)),
                ("cheating_attempts_app", models.BooleanField(default=True)),
                ("supervisor_messages_email", models.BooleanField(default=True)),
                ("supervisor_messages_app", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
