from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("admin-dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("admin-dashboard/users/", views.admin_users, name="admin_users"),
    path("admin-dashboard/users/create/", views.admin_user_create, name="admin_user_create"),
    path("admin-dashboard/teachers/", views.admin_teachers, name="admin_teachers"),
    path("admin-dashboard/teachers/create/", views.admin_teacher_create, name="admin_teacher_create"),
    path("admin-dashboard/groups/", views.admin_groups, name="admin_groups"),
    path("admin-dashboard/exams/", views.admin_exams, name="admin_exams"),
    path("admin-dashboard/exams/<int:exam_id>/monitor/", views.admin_exam_monitor, name="admin_exam_monitor"),
    path("admin-dashboard/exams/<int:exam_id>/results/", views.admin_exam_results, name="admin_exam_results"),
    path("admin-dashboard/exams/<int:exam_id>/details/", views.admin_exam_details, name="admin_exam_details"),
    path("admin-dashboard/analytics/", views.admin_analytics, name="admin_analytics"),
    # API endpoint for syncing exam statuses
    path("api/sync-exam-statuses/", views.sync_exam_statuses_api, name="sync_exam_statuses_api"),
    path("admin-dashboard/settings/", views.admin_settings, name="admin_settings"),
    path("student-dashboard/", views.student_dashboard, name="student_dashboard"),
    path(
        "student-dashboard/teachers/",
        views.student_teachers,
        name="student_teachers",
    ),
    path(
        "student-dashboard/groups/",
        views.student_groups,
        name="student_groups",
    ),
    path(
        "student-dashboard/groups/<int:group_id>/",
        views.student_group_detail,
        name="student_group_detail",
    ),
    path(
        "student-dashboard/exams/<int:exam_id>/result/",
        views.student_exam_result,
        name="student_exam_result",
    ),
    path(
        "student-dashboard/exams/<int:exam_id>/scheduled/",
        views.student_exam_scheduled_detail,
        name="student_exam_scheduled_detail",
    ),
    path(
        "student-dashboard/exams/<int:exam_id>/events/",
        views.student_exam_event,
        name="student_exam_event",
    ),
    path(
        "student-dashboard/exams/<int:exam_id>/notifications/",
        views.student_exam_notifications,
        name="student_exam_notifications",
    ),
    path(
        "student-dashboard/exams/<int:exam_id>/take/",
        views.student_exam_take,
        name="student_exam_take",
    ),
    path(
        "student-dashboard/exams/",
        views.student_exams,
        name="student_exams",
    ),
    path(
        "student-dashboard/join-request/<int:teacher_id>/",
        views.student_send_join_request,
        name="student_send_join_request",
    ),
    path(
        "student-dashboard/invitations/<int:join_request_id>/",
        views.student_invitation_action,
        name="student_invitation_action",
    ),
    path("teacher-dashboard/", views.teacher_dashboard, name="teacher_dashboard"),
    path("teacher-dashboard/groups/", views.teacher_groups, name="teacher_groups"),
    path("teacher-dashboard/groups/create/", views.teacher_group_create, name="teacher_group_create"),
    path("teacher-dashboard/groups/<int:group_id>/", views.teacher_group_detail, name="teacher_group_detail"),
    path("teacher-dashboard/groups/<int:group_id>/edit/", views.teacher_group_edit, name="teacher_group_edit"),
    path("teacher-dashboard/groups/<int:group_id>/delete/", views.teacher_group_delete, name="teacher_group_delete"),
    path("teacher-dashboard/exams/", views.teacher_exams, name="teacher_exams"),
    path("teacher-dashboard/exams/create/", views.teacher_exam_create, name="teacher_exam_create"),
    path("teacher-dashboard/exams/<int:exam_id>/questions/", views.teacher_exam_questions, name="teacher_exam_questions"),
    path("teacher-dashboard/exams/<int:exam_id>/edit/", views.teacher_exam_edit, name="teacher_exam_edit"),
    path("teacher-dashboard/exams/<int:exam_id>/delete/", views.teacher_exam_delete, name="teacher_exam_delete"),
    path("teacher-dashboard/exams/<int:exam_id>/results/", views.teacher_exam_results, name="teacher_exam_results"),
    path("teacher-dashboard/exams/<int:exam_id>/students/<int:student_id>/correction/", views.teacher_exam_student_correction, name="teacher_exam_student_correction"),
    path("teacher-dashboard/exams/<int:exam_id>/monitor/", views.teacher_exam_monitor, name="teacher_exam_monitor"),
    path("teacher-dashboard/exams/<int:exam_id>/monitor/data/", views.teacher_exam_monitor_data, name="teacher_exam_monitor_data"),
    path("teacher-dashboard/exams/<int:exam_id>/monitor/end/", views.teacher_exam_end, name="teacher_exam_end"),
    path("teacher-dashboard/exams/<int:exam_id>/monitor/notify/", views.teacher_exam_notify, name="teacher_exam_notify"),
    path("teacher-dashboard/exams/<int:exam_id>/monitor/students/<int:student_id>/action/", views.teacher_exam_student_action, name="teacher_exam_student_action"),
    
    # Proctor System URLs
    path("proctor/<int:exam_id>/init/", views.proctor_init_session, name="proctor_init_session"),
    path("proctor/<int:exam_id>/snapshot/", views.proctor_upload_snapshot, name="proctor_upload_snapshot"),
    path("proctor/<int:exam_id>/signal/", views.proctor_signal, name="proctor_signal"),
    path("proctor/<int:exam_id>/teacher/signal/<int:student_id>/", views.proctor_teacher_signal, name="proctor_teacher_signal"),
    path("proctor/<int:exam_id>/teacher/snapshots/<int:student_id>/", views.proctor_get_snapshots, name="proctor_get_snapshots"),
    path("proctor/<int:exam_id>/teacher/end/<int:student_id>/", views.proctor_end_session, name="proctor_end_session"),
    path("teacher-dashboard/subjects/<int:subject_id>/exams/create/", views.teacher_exam_create, name="teacher_subject_exam_create"),
    path("teacher-dashboard/subjects/<int:subject_id>/question-bank/", views.teacher_subject_question_bank, name="teacher_subject_question_bank"),
    path("teacher-dashboard/subjects/<int:subject_id>/question-bank/<int:question_id>/edit/", views.teacher_question_edit, name="teacher_question_edit"),
    path("teacher-dashboard/subjects/<int:subject_id>/students/", views.teacher_subject_students, name="teacher_subject_students"),
    path("teacher-dashboard/subjects/<int:subject_id>/edit/", views.teacher_subject_edit, name="teacher_subject_edit"),
    path("teacher-dashboard/subjects/<int:subject_id>/delete/", views.teacher_subject_delete, name="teacher_subject_delete"),
    path("teacher-dashboard/subjects/", views.teacher_subjects, name="teacher_subjects"),
    path("teacher-dashboard/subjects/create/", views.teacher_subject_create, name="teacher_subject_create"),
    path("teacher-dashboard/students/", views.teacher_students, name="teacher_students"),
    path("teacher-dashboard/settings/", views.teacher_settings, name="teacher_settings"),
    path("teacher-dashboard/reports/", views.teacher_reports, name="teacher_reports"),
]
